server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  application:
    name: USER-SERVICE
  profiles:
    active: local
  config:
    import: configserver:http://localhost:8085
